name: Sync Branches

on:
  pull_request:
    types: [closed]
    branches: 
      - develop
      - master

jobs:
  syncing:
    name: Sync branches
    if: (github.base_ref == 'develop' && github.head_ref != 'master') || (github.base_ref == 'master' && startsWith(github.head_ref, 'hotfix/'))
    runs-on: ubuntu-18.04
    env:
      FROM_BRANCH: ${{ github.base_ref }}

    steps:
      - name: Define destiny branch
        run: if [ "${{ github.base_ref }}" = "master" ]; then branch="develop"; else branch="master"; fi; echo "BRANCH=$branch" >> $GITHUB_ENV

      - name: Define PR title
        run: if [ "${{ github.base_ref }}" = "master" ]; then title="Sincronizando master/develop"; else title="Próximo Release"; fi; echo "TITLE=$title" >> $GITHUB_ENV

      - name: Define PR body
        run: if [ "${{ github.base_ref }}" = "master" ]; then body="PR criada automaticamente para sincronização entre branches"; else body="**EDITAR COM AS ALTERAÇÕES FEITAS**"; fi; echo "BODY=$body" >> $GITHUB_ENV

      - name: Creating the PR
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: "${{ env.FROM_BRANCH }}",
              base: "${{ env.BRANCH }}",
              title: "${{ env.TITLE }}",
              body: "${{ env.BODY }}"
            })